### ISSUE TITLE
docker role

### ISSUE THREAD

**Issue by stephenrlouie** [gemini-project/gemini#1]
- docker role needs issues enabled
- docker role needs pxe_coreos branch

**Comment by danehans** [comment]
I enabled issues.

pxe_coreos branch is a temp branch until we can push the changes in pxe_coreos upstream. If you need to make changes to the docker role. Fork the project from upstream, create a local topic branch with a name that is relevant to your changes. Then send a PR upstream. This is similar to how we work in contrib. If the changes don;t get merged upstream, then we can address carrying the patch(es) in the gem fork.
