### ISSUE TITLE
Host the vagrant box

### ISSUE THREAD

**Issue by danehans** [gemini-project/gemini#11]
Currently, users must build the gem-master vagrant box. This takes a long time and does not provide the user experience needed. Create a public-facing site to host vboxes.

/cc: stephenrlouie

**Comment by stephenrlouie** [comment]
Should we still provide instructions on building an image for themselves, or just completely ignore that and always provide a golden image

**Comment by danehans** [comment]
We will want to remove the build instructions and just use the vbox image we host and manage. I'm making progress on hosting the image. It will most like be hosted here: https://bintray.com/

When I confirm, I will provide you instructions for accessing bintray.

**Comment by stephenrlouie** [comment]
I was looking to host on atlas, so we can plug into the vagrant infrastructure.

- Been testing with this: https://atlas.hashicorp.com/stephenrlouie/boxes/gemini_master/
  - Hoping to have something soon

**Comment by stephenrlouie** [comment]
@danehans: Is there anything missing for this issue?

**Comment by danehans** [comment]
Nope, let me close.
