### ISSUE TITLE
K8s version 1.1.4 in master image. upstream is 1.2.0

### ISSUE THREAD

**Issue by stephenrlouie** [gemini-project/gemini#20]
- Version is out of date in default gemini_master image in #18 
- upstream is on 1.2.0, pre-built image has 1.1.4

**Comment by danehans** [comment]
The contrib project changed how k8s bins are downloaded in the following commit, the necessary gemini ansible code should be updated accordingly:

https://github.com/kubernetes/contrib/commit/f5ac9b0f5ac7fe7f63ece8f6a66658adf6bc9ac3
