### ISSUE TITLE
Dynamic group_vars/all.yml via sed

### ISSUE THREAD

**Issue by stephenrlouie** [gemini-project/gemini#22]
- Programatic include of download_urls via sed

**Comment by rutsky** [comment]
@stephenrlouie @danehans do you think sed is best approach for this?

I would expect that Ansible has convenient ways to provide variables overriding, e.g. on [ansible-playbook invocation](https://docs.ansible.com/ansible/playbooks_variables.html#passing-variables-on-the-command-line), or writing files with host-specific variables.

**Comment by danehans** [comment]
@rutsky I think the biggest challenge is separating the contrib/gemini projects. I want to maintain a clean separation for the time being. Take a look at https://github.com/gemini-project/gemini/pull/26 and https://github.com/gemini-project/gemini/pull/27 to see the latest gemini install guide and code changes to see how a gemini/contrib deployment is accomplished using baremetal servers. I am open to your ideas on how we can integrate the gemini/contrib projects while maintaining a clean separation between the two. Maybe we use something like librarian-ansible: https://github.com/bcoe/librarian-ansible to bundle contrib/ansible roles?

**Comment by danehans** [comment]
This issue was resolved suing cat instead of sed: https://github.com/gemini-project/gemini/pull/29

Install doc updated here: https://github.com/gemini-project/gemini/tree/master/docs/install
