### ISSUE TITLE
PYPY tar served on gemini_master

### ISSUE THREAD

**Issue by stephenrlouie** [gemini-project/gemini#5]
This issue refers to the vagrant provisioner

- Add pypy tar fetch to start.sh
- place tar on the apache server
- configure contrib to fetch it from master, not internet

**Comment by danehans** [comment]
@stephenrlouie note that contrib will not aceept any PR's related to the gem-master. See how the flannel and k8s download_url works in contrib and replicate that implementation. You can follow the same approach on gem-master that was implemented for flannel and k8s downloads by exposing the download_url to group_vars.

**Comment by stephenrlouie** [comment]
How do we want to direct users to get these optimizations such as the K8s, flannel and pypy tars since it is not upstream. Possibly cherry-pick some commits from one of our personal contrib projects?

Not sure what would be best since this won't get upstream but is a large optimization we want people to use.

**Comment by danehans** [comment]
@stephenrlouie what we provide and support for users will be a combination of contrib upstrream and other ansible roles outside the contrib project. From a contrib standpoint, we need to follow the design pattern used by flannel/k8s, expose the download url as a group_var. The default for pypy url should be the Internet. See below where we continue the same design pattern in the gemini ansible code:

https://github.com/gemini-project/ansible-role-ansible-controller/blob/master/defaults/main.yml#L20-L24
https://github.com/gemini-project/gemini/blob/master/ansible/group_vars/all.yml#L5-L9
