### ISSUE TITLE
2GB overhead for VMs

### ISSUE THREAD

**Issue by stephenrlouie** [gemini-project/gemini#9]
**hot fix:** Default VM RAM is set to 2GB's but could pose limitations if you want a bigger cluster

- nodes require 2GBs of RAM to work with a simple web app on K8s with 1.75GB gemini will complete its install, but paging errors arise when I tried starting a simple web app. https://gist.github.com/danehans/cb744bd10084175ccc44
- With 1.5GB of RAM. Gemini will fail during its install, probably on download / extraction of a tar.

**Comment by danehans** [comment]
@stephenrlouie is this still an issue? What needs to be done, update docs or something else?

**Comment by stephenrlouie** [comment]
We don't have to call this an issue, its just a note. The default Memory size is set to 2GB right now, and it works.

**Comment by stephenrlouie** [comment]
We don't have to call this an issue, its just a note. The default Memory size is set to 2GB right now, and it works.
